theme: jekyll-theme-primer
title: sixpence
description: ""
baseurl: ""

markdown: CommonMarkGhPages
# see https://github.com/gjtorikian/commonmarker#parse-options
commonmark:
  extensions:
    - autolink
    - strikethrough
